---
collections:
  - ansible.posix
  - community.general

roles:
  - name: inmotionhosting.apache
    version: "1.2.0"

  - name: inmotionhosting.mysql
    version: "1.2.0"

  - name: inmotionhosting.nginx_proxy
    version: "1.1.0"

  - name: inmotionhosting.php_fpm
    version: "1.2.0"

  - name: inmotionhosting.redis
    version: "1.1.0"

  - name: inmotionhosting.letsencrypt
    version: "1.0.2"

  - name: inmotionhosting.wordpress
    version: "1.2.0"

  - name: inmotionhosting.wordpress_ultrastack
    version: "1.1.0"
